# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3318fdad3a0724246764107a94241a3e2626fa0e57a9bd0f45c5f65a8de97290f007ba87620a594e27b0330fb4daca34c505b9173e7cf9e3899c6b3ed3bb09ce

test:
  secret_key_base: ab344fc67d17d51339ff8176c3021c203bf894f46216c02abef37439196cb92d446b5951ff79fa1611e1a27e90993859bae32b392072a50086cd85fec180dde6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
